### ISSUE TITLE
readme.md including install

### ISSUE THREAD

**Issue by mooreniemi** [mlex/karma-spec-reporter#21]
Rather than showing an example project link, why not have install instructions in the readme?

    npm install karma-spec-reporter --save-dev
then add 'spec' to reporters in karma.conf.js, ala 

    reporters: ['progress','coverage', 'spec'],

**Comment by caffed** [comment]
I'd like to note that I had to remove progress from the reporters array for it show up correctly.

Karma version 0.12.31
Karma-spec-reporter 0.0.16

Before:
```javascript
...
  reporters: ['progress', 'spec', 'coverage'],
...
```

After:
```javascript
...
  reporters: ['spec','coverage'],
...
```
