### ISSUE TITLE
Windows encoding issue for success and failure symbols

### ISSUE THREAD

**Issue by Francisc** [mlex/karma-spec-reporter#28]
Hello,

Is there any config to change the success / failure symbol?

This is how it looks in a capable (MinGW) Windows console.
![ss](https://cloud.githubusercontent.com/assets/699657/7133686/98436b4c-e29e-11e4-8d7c-ea76140547df.jpg)

**Comment by Francisc** [comment]
Echo!

**Comment by mlex** [comment]
You can change the symbols with the `specReporter.prefixes.[success|failure|skipped]`  config option. Just add the following to your karma.conf.js:

```javascript
specReporter : {
        prefixes : {
            success: 'O ',
            failure: 'X ',
            skipped: '_ '
        }
  }
```

Please make sure, that you add all three symbols. Otherwise, the reporter will crash with a `cannot read ... of undefined` error.

**Comment by Francisc** [comment]
Should have seen that, thank you.
