### ISSUE TITLE
Should Not show skipped spec in console

### ISSUE THREAD

**Issue by lovedota** [mlex/karma-spec-reporter#31]
Hi guys
When i use with *Karma-Jasmine* with *fdescribe, fiit*, it stills shows all the spec in console.
```
 LastMileAssignRunsheetViewStore
    ✓ should return empty runsheets at the beginning
    ✓ should return edit mode = false at the beginning
    ✓ should subscribing LOADING_DRIVERS_SUCCESS event
    Case subscribing SELECT_DRIVER
      ✗ Should add packages to runsheet
        TypeError: 'undefined' is not an object (evaluating 'LastMileAssignRunsheetViewStore.runsheets['123'].packages')
            at /stores/LastMileAssign/__tests__/LastMileAssignRunsheetViewStore-test.js:139

  ErrorAlertComponent
    - Should not render ErrorAlertComponent if store has no error
    - Should render ErrorAlertComponent if store has error


```

**Comment by hdavidzhu** [comment]
@lovedota For the time being, I think the alternative supports this feature.
https://www.npmjs.com/package/karma-spec-reporter-2

**Comment by mlex** [comment]
Hi @hdavidzhu, would you like to take over the karma-spec-reporter from me? I actually didn't execute karme once in the last year, so I don't feel like I can continue this little project. I can transfer ownership of the npmjs project if you want.

**Comment by mlex** [comment]
There is already a configuration option to not show skipped tests:
```
config.set({
  specReporter: {
    suppressSkipped: true
  }
})
```

Is this what you are looking for?

**Comment by hdavidzhu** [comment]
@mlex sure thing I'd love to help

**Comment by mlex** [comment]
Ok. I added you as collaborator and as owner of the npm project.
