### ISSUE TITLE
As a developer, I need automated testing so I can make changes with confidence.

### ISSUE THREAD

**Issue by tmcgee123** [mlex/karma-spec-reporter#36]

**Comment by hdavidzhu** [comment]
What's the best way for us to go about this? Build index.js from other files, and test those files separately?

**Comment by tmcgee123** [comment]
How do you feel about pulling in Mocha for testing? https://mochajs.org/

**Comment by hdavidzhu** [comment]
I'm a fan of Mocha. We might have to modularize parts of the code first to get them in isolation for testing. Thoughts?

**Comment by tmcgee123** [comment]
It looks like most of the code is in functions. I think we would benefit from even more modular code though. I think we should also have a code coverage reporter for reference as well, so we know we can account for each piece of functionality.

**Comment by tmcgee123** [comment]
I'll close this issue once we have CI to enforce that the tests will pass. This really doesn't fall in the category of "automated" testing since we are not using a task runner to run the tests while developing, but I'm not sure if it would be worth it since this module is so small. Any thoughts?

**Comment by hdavidzhu** [comment]
Yeah no need to go overboard :stuck_out_tongue: just enough to be useful

**Comment by hdavidzhu** [comment]
thanks for the setup @tmcgee123

**Comment by tmcgee123** [comment]
Anytime! I've been on a unit testing kick for the past year or so :smiley:
