### ISSUE TITLE
As a developer, I need continuous integration for building the project.

### ISSUE THREAD

**Issue by tmcgee123** [mlex/karma-spec-reporter#38]
CI will allow us to enforce code coverage standards and enable us to catch any errors that may happen when anyone makes changes.

**Comment by hdavidzhu** [comment]
codeship, travis, or something else?

**Comment by tmcgee123** [comment]
I think Travis would work well, that seems to be the standards across GitHub at least. Any thoughts?

**Comment by hdavidzhu** [comment]
:+1: sounds good

**Comment by mlex** [comment]
I added a .travis.yml and activated travis for the project. Seems to run fine :-)
https://travis-ci.org/mlex/karma-spec-reporter/builds/90263003

**Comment by hdavidzhu** [comment]
@mlex thanks
