### ISSUE TITLE
As a developer, I'd like code coverage integrated into CI so I can have visibility to the coverage of the project.

### ISSUE THREAD

**Issue by tmcgee123** [mlex/karma-spec-reporter#39]
Currently, we have the ability to generate code coverage with istanbul. I've looked around and found that Code Climate has integration with Travis CI and the nice badge for us to add to the README. Here's the [link to their website](https://codeclimate.com/).

[Here's the link for getting it set up with Travis.](http://docs.travis-ci.com/user/code-climate/)

I plan on spending time this week to get our coverage up to acceptable standards. I really like to use these coverage reports as it helps identify potential points for refactoring and gives a nice reading as to what has been tested.

Any thoughts or concerns?

**Comment by hdavidzhu** [comment]
:+1: code coverage is always good

**Comment by tmcgee123** [comment]
@mlex I think you have to set it up since you own the GitHub Project.

**Comment by mlex** [comment]
I just had a look at codeclimate. When trying to sign up, it asks extensive github privileges (e.g. access too all public and *private* repositories from me and *all my organizations*). This is too much. I will check this weekend, if I can find a way to set it up without giving codeclimate access to all my private repos.

Has anybody already worked with codeclimate?

**Comment by tmcgee123** [comment]
I noticed that it required extensive privileges as well. I have no personal ties to codeclimate so I am in favor of what ever works with the least amount of friction. Thanks for looking into @mlex !

**Comment by mlex** [comment]
I added support for coveralls (including a nice batch), which also publishes coverage reports (and requires fewer privileges).
