### ISSUE TITLE
As a developer, when running tests with the colors option set to false in IntelliJ 15, escape char's are not being outputted correctly.

### ISSUE THREAD

**Issue by amitport** [mlex/karma-spec-reporter#44]
running a failing test with 'colors: false' messes-up output in some consoles (e.g., intelliJ run console)

**Comment by hdavidzhu** [comment]
Could you copy/paste the output?

**Comment by amitport** [comment]
```
Chrome 47.0.2526 (Windows 7 0.0.0): Executed 2 of 2 (1 FAILED) (0.028 secs / 0.001 secs)
TOTAL: 1 FAILED, 1 SUCCESS

[31m1) <test-name>
[39m[31m     <test scope>
[39m     [90mAssertionError: expected 1 to equal 10
    at Context.<anonymous> (<file-path>:25:32)
[39m
```

**Comment by tmcgee123** [comment]
Seems to be fixed with IntelliJ 14. What version are you using?

Also, when you say messes up, is it the formatting? Are colors still displaying? It would be awesome if you could post a screenshot instead of just the output.

**Comment by amitport** [comment]
using intelliJ 15 here. formatting is OK, no colors. just the weird `�[31m`, `�[90m` chars all over the area that supposed to be red.

Just in case it may help, I'll add some more possibly _unrelated and over-complicating_ details:  I'm running karma as a [gradle-exec](https://docs.gradle.org/current/dsl/org.gradle.api.tasks.Exec.html) [task](https://www.jetbrains.com/idea/help/working-with-gradle-tasks-in-gradle-tool-window.html) on windows. When using intelliJ terminal the output is OK, I'm only seeing issues on the intelliJ's gradle-task output.

In any case, I don't want to fix intelliJ issues here- but if I could make karma output without any color, that is, **no red on errors**, I think this will solve the output issues intelliJ has

**Comment by tmcgee123** [comment]
Thank you for the clarification @amitport, I will look into this if @hdavidzhu doesn't get to it first!

**Comment by tmcgee123** [comment]
Closing this as only one person has made an issue or said anything in the last 2 years, if it comes back up I will open the ticket again.
