### ISSUE TITLE
As a developer, when using a module loader failed tests are not being reported correctly.

### ISSUE THREAD

**Issue by IngwiePhoenix** [mlex/karma-spec-reporter#45]
Basically, I want them.

Since I use `karma-webpack` in order to roll my tests through my WebPack config, I urgently need to be able to see backtraces. Because of some preprocessors, lines have an offset, or I get to see the wrong file entirely! But the backtrace itself would solve many, many problems.

That files arent displayed correctly is a `karma-webpack` thing, fo' sho'. But having no idea where an error is coming from is problematic.

How can I get them?

Also... https://lh4.googleusercontent.com/-APYsZ_NfGTc/TsV4umugivI/AAAAAAAAFok/dgi1WC6Aw6c/w800-h800/687474703a2f2f692e696d6775722e636f6d2f6a61636f6a2e6a7067.jpg

**Comment by tmcgee123** [comment]
Are you not getting any type of reporting at all? Can you post your karma.config.js please?

Unfortunately, I've never used a webpack before. karma-spec-reporter is a reporter, not a preprocessor. I'm not sure what relation the preprocessor has to the reporter, as they are supposed to be two completely different plugins, I'll have to do some digging.

Any type of information, examples, console output, or further explanations would help a lot! We might need to collaborate to help get this working, I completely understand the need for a solid stacktrace!

**Comment by tmcgee123** [comment]
@IngwiePhoenix have you tried bumping the version that it used in karma-webpack to the latest release? It looks like they are a few versions behind. Let me know if that works!!

**Comment by tmcgee123** [comment]
@IngwiePhoenix please verify that with the latest karma that you are still not seeing reporting, this was actually a recent defect that was just fixed: https://github.com/karma-runner/karma/issues/1894

**Comment by tmcgee123** [comment]
Closing since no one else has verified that this is still an issue. I'll re-open if that's not the case.
