### ISSUE TITLE
No console output with karma v0.13.20

### ISSUE THREAD

**Issue by twmills** [mlex/karma-spec-reporter#48]
After upgrading to karma v0.13.20 I no longer see any console output. Works fine in v0.13.19.

**Comment by dan-f** [comment]
I'm seeing the same behavior.

**Comment by urbaitel** [comment]
Me too!   Just downgrade to v0.13.19 and it worked.

**Comment by bertrandjamin** [comment]
I had the same problem with karma v0.13.20 but it's fixed the new karma v0.13.21 (https://github.com/karma-runner/karma/releases/tag/v0.13.21)

**Comment by tmcgee123** [comment]
Please do as **bertandjamin** instructed and update to the latest karma release.

Closing this as it was a defect with karma that broke third-party support for reporters, related to these issues on the karma repository: [#1894](https://github.com/karma-runner/karma/issues/1894) and [#1895](https://github.com/karma-runner/karma/issues/1895)

Thanks all!
