### ISSUE TITLE
As a developer, when running tests on windows, I would like to see checkmarks

### ISSUE THREAD

**Issue by konsumer** [mlex/karma-spec-reporter#52]
The ✔/✖ chars show up as boxes in `CMD`. Mocha [got around this](https://github.com/mochajs/mocha/pull/641) by using fallbacks of √ instead of ✔, × instead of ✖

![test](https://cloud.githubusercontent.com/assets/83857/14029093/5c4e690a-f1bd-11e5-9164-e8c16596e6dc.gif)

**Comment by tmcgee123** [comment]
Much thanks @konsumer, I will be getting to this soon.

**Comment by tmcgee123** [comment]
Hey @konsumer, would you mind being my tester for me? I'm going to push a branch that I'd like you to pull down (I'm not on a Windows machine currently). The branch will be feature/windows-icons.

**Comment by konsumer** [comment]
Looks good! This is in standard CMD:
![test](https://cloud.githubusercontent.com/assets/83857/14360291/7a1f0604-fcaa-11e5-8959-976fc1406d87.gif)

Thanks for the fast fix!

For others coming here from google, I also solved it by using [ConEmu](https://conemu.github.io/)

**Comment by tmcgee123** [comment]
Awesome! Now I just have to tackle the testing, unfortunately it involves some changes with mocking so working to resolve that (I'm used to Jasmine, Mocha is so strange).

**Comment by mitorez** [comment]
Maybe not the best place to ask this question, but is there a way to turn off check marks when piping to a text file? They make the file appear to be a non-text file when loaded into Atlassian Crucible. Thanks!
