### ISSUE TITLE
wrong version published to NPM

### ISSUE THREAD

**Issue by UnsungHero97** [mlex/karma-spec-reporter#53]
It seems like the version published as `0.0.24` doesn't match what's on GitHub. I've installed `0.0.24` locally, but it doesn't have any code for `showSpecTiming`. It still has the `TODO` on line 85:

    //TODO: add timing information

Was the wrong version published to NPM?

**Comment by tmcgee123** [comment]
Just published v0.0.25 for ya, sorry, I never updated the version on NPM.

**Comment by UnsungHero97** [comment]
no worries. thanks for the super quick response!
