### ISSUE TITLE
As a test reporter, I'd like to see just the tests and pass/fail.

### ISSUE THREAD

**Issue by captainstarfish** [mlex/karma-spec-reporter#60]
Suggestion: add a "summaryOnly" boolean config flag. When set, this suppresses the error summary and effectively sets the maxLogLines to 0. So we see all the "describe" lines, all the "it" lines decorated with colour and tick/cross for pass/fail, and that's it.

**Comment by captainstarfish** [comment]
The attached patch seems to work against commit a71f679.
[summaryOnly.patch.txt](https://github.com/mlex/karma-spec-reporter/files/451026/summaryOnly.patch.txt)

**Comment by tmcgee123** [comment]
@captainstarfish is this still needed? Can you put together a PR?

**Comment by tmcgee123** [comment]
Closing and referencing in new ticket
