### ISSUE TITLE
I have to install this package

### ISSUE THREAD

**Issue by megamindbrian** [mlex/karma-spec-reporter#67]
Why do I have a separate install for something that should be included by default?
I need to view a list of passing and failing tests.  Period.

**Comment by FjVillar** [comment]
When you say it should be included by default you're saying that it should be included in Karma by default?. I think thats not the meaning of the reporters in Karma but... if you think that,  this in not the right place to say it. You should go over to Karma's repo or you should make a PR.

**Comment by tmcgee123** [comment]
@FjVillar is correct, closing now. @megamindbrian, if you find out there's a change we need to make please submit a PR.

**Comment by megamindbrian** [comment]
So none of you are willing to admit there are too many npm packages to do
really simple things?

**Comment by tmcgee123** [comment]
@megamindbrian this is not the place for a discussion. If you want to discuss the pros and cons of package management systems then https://stackexchange.com/ might be your place. I understand your frustration, but there's limited things I can do.

The karma repo is located here: https://github.com/karma-runner/karma

Again, make sure this is the repo that is missing the karma-spec-reporter dependency in their package.json and that should be your culprit.

If you're looking for someone to share your pain with you, this happened a while ago and brought attention to the matter you are talking about: http://blog.npmjs.org/post/141577284765/kik-left-pad-and-npm
