### ISSUE TITLE
I've combined this project with Karma

### ISSUE THREAD

**Issue by megamindbrian** [mlex/karma-spec-reporter#68]
@FjVillar Here is the pull request you asked for earlier:
https://github.com/karma-runner/karma/pull/2742

I hope it gets through at some point...

**Comment by FjVillar** [comment]
Hi @megamindbrian, I would say that im happy for the PR but I didn't asked for it. Just a question: what's your aim? Is it to get Karma to use karma-spec-reporter by default ? This seems a good idea for me ofcourse because integrate this package on Karma's could be nice.

**Comment by megamindbrian** [comment]
Yes. It is like when I open a new box I want something useful to pop out.
If I am debugging with karma I can't tell what test have run or what error
goes with what test. Your index.js files fixes all that.
Dots and progress are pointless for debugging, the spec reporter gives a
more classic experience, much like NUnit or JUnit.

**Comment by megamindbrian** [comment]
I didn't know karma was managed by Google. No wonder no one has time to
make it better, everyone at Google has moved on to ruling the world like in
the movies the circle:
https://www.rottentomatoes.com/m/the_circle_2017/

**Comment by megamindbrian** [comment]
Which one should we combine next?

https://github.com/AngularClass/angular-starter/blob/master/package.json

**Comment by Narretz** [comment]
Idk but for me "progress" (the default) definitely reports failed tests and their stacktraces (in an AngularJS project)

**Comment by tmcgee123** [comment]
Please don't open another issue for this, we've already determined that this doesn't belong here
