### ISSUE TITLE
Printing [32m✓ [39m in jenkins console

### ISSUE THREAD

**Issue by gnusiva** [mlex/karma-spec-reporter#84]
hi, in local machine is printing the tick character correctly. but in jenkins it is printing as ` [32m✓ [39m ` while viewing in web browser. Is there any configuration to change the tick mark?

**Comment by coyoteecd** [comment]
@gnusiva there is an undocumented prefixes configuration object, see https://github.com/mlex/karma-spec-reporter/pull/24.

Example usage (from karma.conf.js):
```
    specReporter: {
      showSpecTiming: true,
      suppressSkipped: true,
      prefixes: {
        success: '    OK: ',
        failure: 'FAILED: ',
        skipped: 'SKIPPED: '
      },
    },
```

**Comment by tva-TIS** [comment]
That changes the tickmark, but thats not the reason, jenkins is struggling with the output (`[32m✓ [39m` **does** contain the tickmark). The problem are the ansi colors. You can either disable those with `--no-colors` (or `colors: false` or `noColors: true` in the karma configuration file) or you install the Jenkins ANSI plugin <https://plugins.jenkins.io/ansicolor/>.
